alias ls="ls --group-directories-first -h --color=always"
alias gpg="gpg2"
alias emacs="emacs -nw"
alias zathura="unshare -n -r zathura --fork"
alias ncdu="ncdu --color dark -x -rr"
alias beep="play -q -n synth 0.1 sin 680 || echo -e '\a'"
alias vim="nvim -p"
alias vi="vim"
alias unfold="tr -d '\n'"
alias base64="base64 -w0"
alias gopass="unshare -n -r gopass"
alias pass="gopass"
alias preview="fzf --preview='cat {}' --preview-window=right:70%:wrap"
alias p="fzf --preview='cat {}' --preview-window=right:70%:wrap"
alias dh="sed 1d"
